Feature: Player Teleport
JennyKmu/RRO_savefile_editor pull request #42
Opened 2021-11-20 19:54 UTC by Leif-The-Head

Move any player to:
* Spawn
* Any industry
* Any Firewood depot
* Any other player

Also in this update:
* A few fixes
* Rolling Stock: Replace Flatcars with other Flatcar types
* DEV Feature: Edit Industry's Locations

2021-11-20 19:55 UTC, Leif-The-Head commented on RRO_savefile_editor/UI/ui.py
> +dev_version = True
When releasing this should be set to False aswell

2021-11-20 19:56 UTC, Leif-The-Head commented on RRO_savefile_editor/UI/ui.py
> +            ("Move Industries", moveindustries),
This is not available outside of DEV on purpose, I may hand out single versions when asked for

2021-11-21 07:59 UTC, JennyKmu commented on RRO_savefile_editor/UI/ui.py
> +            ("Move Industries", moveindustries),
The Dev Slots should be conserved when dev_version is True (since it gives a nice way to create temporary "features" for testing when developing)

2021-11-21 08:01 UTC, JennyKmu commented on RRO_savefile_editor/UI/ui.py
> +dev_version = True
Unless it is used somewhere else than in the mainMenu, it is not needed in this file since it is passed as argument for the mainMenu from the main.py file.

2021-11-21 08:05 UTC, JennyKmu requested changes
Good work ! A few details need to be addressed before merging (concerning dev slots, dev_version variable, and default value for the loop function, see comments)

2021-11-21 08:05 UTC, JennyKmu commented on RRO_savefile_editor/main.py
> +    def loop(loc="./sav_respawn_players/shop/."):
The default value should not change when pushed to dev_xxx branches

2021-11-25 10:41 UTC, Leif-The-Head commented on RRO_savefile_editor/UI/ui.py
> +dev_version = True
I did use it elsewhere, but converted it to a global that is changed by the call from the mainMenu

2021-11-26 19:36 UTC, JennyKmu approved these changes

2021-11-26 19:36 UTC, merged